name: Fix code style

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ master ]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    strategy:
        fail-fast: false
        matrix:
            php: ["8.1", "8.0"]
            laravel: ["^9.0", "^8.0"]
            stability: [prefer-lowest, prefer-stable]

    name: PHP${{ matrix.php }} — Laravel ${{ matrix.laravel }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: ${{ matrix.php }}
            extensions: gd

      - name: Install dependencies
        run: |
            composer require "laravel/framework:${{ matrix.laravel }}" --dev --no-interaction --no-update
            composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Fix code style
        run: composer fix

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: Apply CS fixes
