name: Run tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    name: PHP${{matrix.php}} — L${{matrix.laravel}} — ${{matrix.stability}}

    strategy:
      matrix:
        php: [8.1, 8.0]
        laravel: [9.*, 8.*]
        stability: [prefer-lowest, prefer-stable]
        exclude:
          # PHP 8.1 is not supported on Laravel 8
          - laravel: 8.*
            php: 8.1
          # PHP 8.0 was not supported on initial Laravel 8 versions
          - laravel: 8.*
            php: 8.0
            stability: prefer-lowest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.php}}

      - name: Install dependencies
        run: |
            composer require "laravel/framework:${{ matrix.laravel }}" --no-update
            composer update --${{ matrix.stability }} --prefer-dist

      - name: Run tests
        run: composer test
